@echo off
echo Inicializando repositorio...
git init
echo Anadiendo archivos...
git add .
echo Creando commit...
git commit -m "Respaldando el proyecto actual"
echo Cambiando a la rama main...
git branch -M main
echo Configurando el remote origin...
git remote add origin https://github.com/mfvaldiviezo/podia_julio_26.git 2>nul || git remote set-url origin https://github.com/mfvaldiviezo/podia_julio_26.git
echo Subiendo los cambios a GitHub...
git push -u origin main
echo.
echo Proceso finalizado. Puedes cerrar esta ventana.
pause
